#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx512m -Xms128m"

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
    done
SAVED="`pwd`"
cd "`dirname "$PRG"`/"
APP_HOME="`pwd -P`"
cd "$SAVED"

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if [ "$cygwin" = "true" -o "$darwin" = "true" -o "$msys" = "true" ] ; then
    ulimit -n 2048 >/dev/null 2>&1
else
    case `uname` in
        CYGWIN* ) cygwin=true ;;
        MINGW* ) msys=true ;;
        Darwin* ) darwin=true ;;
        * ) ;;
    esac
    ulimit -n 1024 >/dev/null 2>&1
fi

# For Darwin, add the Apple JDK to the path to be able to use java_home
if [ "$darwin" = "true" ] ; then
    if [ -z "$JAVA_HOME" ] ; then
        if [ -x "/usr/libexec/java_home" ] ; then
            JAVA_HOME=`/usr/libexec/java_home`
        fi
    fi
fi

# For Cygwin, switch paths to Windows format before running java
if [ "$cygwin" = "true" -o "$msys" = "true" ] ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    for arg in "$@" ; do
        if [ -z "$APP_ARGS" ] ; then
            APP_ARGS="$arg"
        else
            APP_ARGS="$APP_ARGS"" "$arg"
        fi
    done

    # Now convert the arguments to Windows paths.
    eval set -- `cygpath --path --ignore --mixed "$APP_ARGS"`
fi

# Escape application args
save () {
    for i in "$@" ; do
        printf %s\n "$i" | sed "s/'/'\\''/g"
    done
}
APP_ARGS=`save "$@"`

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

exec "$JAVACMD" "$@"
